
                ifndef _CORE_MODULE_GRAPHICS_CAR_2_INCLUDE_
                define _CORE_MODULE_GRAPHICS_CAR_2_INCLUDE_

                module Car_B

Anim_0          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_0.spr"
Anim_1          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_1.spr"
Anim_2          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_2.spr"
Anim_3          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_3.spr"
Anim_4          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_4.spr"
Anim_5          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_5.spr"
Anim_6          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_6.spr"
Anim_7          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_7.spr"
Anim_8          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_8.spr"
Anim_9          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_9.spr"
Anim_A          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_A.spr"
Anim_B          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_B.spr"
Anim_C          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_C.spr"
Anim_D          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_D.spr"
Anim_E          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_E.spr"
Anim_F          incbin "Core/Module/Graphics/Car/B/Sprite/Original/Car_1_F.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_CAR_2_INCLUDE_
