
                ifndef _CORE_MODULE_GAME_UI_CHARECTER_INCLUDE_
                define _CORE_MODULE_GAME_UI_CHARECTER_INCLUDE_

                module Charecter

                include "Tick.asm"
                include "State_None.asm"
                include "State_Idle.asm"
                include "State_Tolk.asm"

                endmodule

                endif ; ~_CORE_MODULE_GAME_UI_CHARECTER_INCLUDE_
