
                ifndef _CORE_MODULE_GRAPHICS_MUZZLE_FLASH_INCLUDE_
                define _CORE_MODULE_GRAPHICS_MUZZLE_FLASH_INCLUDE_

                module MuzzleFlash
Anim_0_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_0_0.spr"
Anim_0_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_0_1.spr"
Anim_1_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_1_0.spr"
Anim_1_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_1_1.spr"
Anim_2_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_2_0.spr"
Anim_2_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_2_1.spr"
Anim_3_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_3_0.spr"
Anim_3_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_3_1.spr"
Anim_4_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_4_0.spr"
Anim_4_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_4_1.spr"
Anim_5_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_5_0.spr"
Anim_5_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_5_1.spr"
Anim_6_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_6_0.spr"
Anim_6_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_6_1.spr"
Anim_7_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_7_0.spr"
Anim_7_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_7_1.spr"
Anim_8_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_8_0.spr"
Anim_8_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_8_1.spr"
Anim_9_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_9_0.spr"
Anim_9_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_9_1.spr"
Anim_A_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_A_0.spr"
Anim_A_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_A_1.spr"
Anim_B_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_B_0.spr"
Anim_B_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_B_1.spr"
Anim_C_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_C_0.spr"
Anim_C_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_C_1.spr"
Anim_D_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_D_0.spr"
Anim_D_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_D_1.spr"
Anim_E_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_E_0.spr"
Anim_E_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_E_1.spr"
Anim_F_0        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_F_0.spr"
Anim_F_1        incbin "Core/Module/Graphics/VFX/MuzzleFlash/Original/MuzzleFlash_F_1.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_MUZZLE_FLASH_INCLUDE_
