
                module SpriteInfo 
MuzzleFlash:            
                FSprite { { 9,  0-6,  8,  0+12 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_0_0 } }
                FSprite { { 8,  0-5,  8,  0+12 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_0_1 } }
                FSprite { { 8,  0-5,  6,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_1_0 } }
                FSprite { { 8,  0-5,  6,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_1_1 } }
                FSprite { { 6,  0-4,  6,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_2_0 } }
                FSprite { { 7,  0-4,  7,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_2_1 } }
                FSprite { { 6,  0-4,  8,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_3_0 } }
                FSprite { { 7,  0-4,  9,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_3_1 } }
                FSprite { { 7,  0-1, 11,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_4_0 } }
                FSprite { { 7,  0-1, 10,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_4_1 } }
                FSprite { { 7,  0+2,  8,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_5_0 } }
                FSprite { { 6,  0+2,  9,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_5_1 } }
                FSprite { { 6,  0+2,  6,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_6_0 } }
                FSprite { { 7,  0+2,  7,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_6_1 } }
                FSprite { { 7,  0+2,  6,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_7_0 } }
                FSprite { { 8,  0+2,  6,  0+16 }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_7_1 } }
                FSprite { { 9,  0+2,  7,  4+9  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_8_0 } }
                FSprite { { 9,  0+2,  6,  4+9  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_8_1 } }
                FSprite { { 9,  0+2,  6,  4+8  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_9_0 } }
                FSprite { { 8,  0+2,  7,  4+8  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_9_1 } }
                FSprite { { 8,  0+2,  8,  8+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_A_0 } }
                FSprite { { 8,  0+2,  8,  8+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_A_1 } }
                FSprite { { 7,    0, 16,  0+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_B_0 } }
                FSprite { { 7,    0, 16,  0+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_B_1 } }
                FSprite { { 7,  3-6, 16,  0+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_C_0 } }
                FSprite { { 7,  3-6, 16,  0+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_C_1 } }
                FSprite { { 6,  6-9, 16,  0+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_D_0 } }
                FSprite { { 6,  6-9, 16,  0+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_D_1 } }
                FSprite { { 8, 8-13,  8,  8+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_E_0 } }
                FSprite { { 8, 8-13,  8,  8+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_E_1 } }
                FSprite { { 8, 8-13,  8,  8+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_F_0 } }
                FSprite { { 8, 8-13,  8,  8+1  }, 0, { Page.Graphics.Pack1, Graphics.MuzzleFlash.Anim_F_1 } }

                endmodule
