
                ; compressor    https://github.com/emmanuel-marty/salvador
                ; decompressor  https://github.com/einar-saukas/ZX0
                
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Map/Original/Frame_0.spr Core/Module/Graphics/UI/Map/Compressed/Frame_0.spr.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Map/Original/Frame_1.spr Core/Module/Graphics/UI/Map/Compressed/Frame_1.spr.ar"
