
                ifndef _MODULE_GAME_RENDER_INCLUDE_
                define _MODULE_GAME_RENDER_INCLUDE_

                module Render
                
                include "World/Include.inc"
                include "Pause/Include.inc"

                include "Sort/Include.inc"
                include "Swap.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_INCLUDE_
