
                ifndef _CORE_MODULE_OPEN_WORLD_OBJECT_COLLISION_AABB_INCLUDE_
                define _CORE_MODULE_OPEN_WORLD_OBJECT_COLLISION_AABB_INCLUDE_
                
                module AABB

                include "GetAABB.asm"
                include "Pawn.asm"
                include "Decal.asm"
                include "Mine.asm"

                endmodule

                endif ; ~_CORE_MODULE_OPEN_WORLD_OBJECT_COLLISION_AABB_INCLUDE_
