
                ifndef _MODULE_GAME_RENDER_SETTLEMENT_INCLUDE_
                define _MODULE_GAME_RENDER_SETTLEMENT_INCLUDE_

                module Render

                include "Draw.asm"
                include "DisplayTime.asm"
                include "DisplayFrame.asm"
                include "DisplayScroll.asm"
                include "DisplayArtFrame.asm"
                include "DisplayLocation.asm"
                include "DisplayCharecter.asm"
                include "DisplayBuildList.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_SETTLEMENT_INCLUDE_
