
                module SpriteInfo
Car:           
                FSprite { { 18, 2, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_4 } }       ; 0000 - 0.0°     right
                FSprite { { 22, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_3 } }       ; 0001 - 22.5°
                FSprite { { 24, 0, 23, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_2 } }       ; 0010 - 45.0°    up-right
                FSprite { { 24, 0, 21, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_1 } }       ; 0011 - 67.5°
                FSprite { { 22, 1, 16, 4 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_0 } }       ; 0100 - 90.0°    up
                FSprite { { 24, 0, 21, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_F } }       ; 0101 - 112.5°
                FSprite { { 24, 0, 23, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_E } }       ; 0110 - 135.0°   up-left
                FSprite { { 22, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_D } }       ; 0111 - 157.5°

                FSprite { { 18, 2, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_C } }       ; 1000 - 180.0°   left
                FSprite { { 22, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_B } }       ; 1001 - 202.5°
                FSprite { { 23, 0, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_A } }       ; 1010 - 225.0°   down-left
                FSprite { { 23, 0, 20, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_9 } }       ; 1011 - 247.0°
                FSprite { { 22, 1, 16, 4 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_8 } }       ; 1100 - 270.0°   down
                FSprite { { 23, 0, 20, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_7 } }       ; 1101 - 292.5°
                FSprite { { 23, 0, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_6 } }       ; 1110 - 315.0°   down-right
                FSprite { { 20, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_5 } }       ; 1111 - 337.5°

                endmodule
