
                module SpriteInfo

Data:           FSprite { { 22, 1, 16, 4 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_0 } }
                FSprite { { 24, 0, 21, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_1 } }
                FSprite { { 24, 0, 23, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_2 } }
                FSprite { { 22, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_3 } }
                FSprite { { 18, 2, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_4 } }
                FSprite { { 20, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_5 } }
                FSprite { { 23, 0, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_6 } }
                FSprite { { 23, 0, 20, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_7 } }

                FSprite { { 22, 1, 16, 4 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_8 } }
                FSprite { { 23, 0, 20, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_9 } }
                FSprite { { 23, 0, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_A } }
                FSprite { { 22, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_B } }
                FSprite { { 18, 2, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_C } }
                FSprite { { 22, 1, 24, 0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_D } }
                FSprite { { 24, 0, 23, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_E } }
                FSprite { { 24, 0, 21, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car.Anim_F } }

                endmodule
