
                module SpriteInfo

Data:           FSprite { { 22, 1, 16,  4 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_0 } }
                FSprite { { 24, 0, 21,  2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_1 } }
                FSprite { { 24, 0, 23,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_2 } }
                FSprite { { 22, 1, 24,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_3 } }
                FSprite { { 18, 2, 24,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_4 } }
                FSprite { { 20, 1, 24,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_5 } }
                FSprite { { 23, 0, 24,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_6 } }
                FSprite { { 23, 2, 20,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_7 } }

                FSprite { { 22, 1, 24,  4 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_8 } }
                FSprite { { 24, 0, 23,  2 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_9 } }
                FSprite { { 24, 0, 22,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_A } }
                FSprite { { 20, 1, 24,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_B } }
                FSprite { { 18, 2, 24,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_C } }
                FSprite { { 20, 1, 24,  0 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_D } }
                FSprite { { 24, 0, 23,  1 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_E } }
                FSprite { { 24, 0, 21,  1 }, 0, { Page.Graphics.Pack1, Graphics.Car.Aim_F } }

                endmodule
