
                ifndef _MODULE_GAME_RENDER_WASTELAND_UI_INCLUDE_
                define _MODULE_GAME_RENDER_WASTELAND_UI_INCLUDE_

                module UI

                include "Bars.asm"
                include "Slot.asm"
                include "Icons.asm"
                include "Draw.asm"
                include "Frame.asm"
                include "Initialize.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_WASTELAND_UI_INCLUDE_
