
                ifndef _BUILDER_GAME_PACKS_
                define _BUILDER_GAME_PACKS_

                include "Pages/Pack 0.inc"
                include "Pages/Pack 1.inc"
                include "Pages/Pack 2.inc"
                include "Pages/Pack 3.inc"
                include "Pages/Pack 4.inc"
                include "Pages/Pack 5.inc"
                include "Pages/Pack 6.inc"

                endif ; ~ _BUILDER_GAME_PACKS_
