
                ifndef _MACRO_INCLUDE_
                define _MACRO_INCLUDE_

                include "Basic.inc"
                include "Flags.inc"
                include "World.inc"
                include "Debug.inc"
                include "Screen.inc"
                include "Memory.inc"
                include "Player.inc"
                include "Render.inc"
                include "Game.inc"
                include "Hardware.inc"
                include "Gameplay.inc"
                include "Interrupt.inc"
                include "Config_Graphics.inc"

                endif ; ~_MACRO_INCLUDE_
