
                ifndef _MACRO_INCLUDE_
                define _MACRO_INCLUDE_

                include "Basic.inc"
                include "Screen.inc"
                include "Memory.inc"
                include "Interrupt.inc"
                include "Flags.inc"
                include "World.inc"
                include "Render.inc"
                include "Player.inc"
                include "Debug.inc"

                endif ; ~_MACRO_INCLUDE_
