
                ifndef _MODULE_GAME_OBJECT_INCLUDE_
                define _MODULE_GAME_OBJECT_INCLUDE_

                module Object
                
                include "Tick.asm"
                include "Update.asm"
                include "Player/Include.inc"
                include "NPC/Include.inc"
                include "Decal.asm"
                include "Particle.asm"

                endmodule

                endif ; ~_MODULE_GAME_OBJECT_INCLUDE_
