
                ifndef _MODULE_GAME_OBJECT_COLLISION_INCLUDE_
                define _MODULE_GAME_OBJECT_COLLISION_INCLUDE_

                module Collision
                
                include "Collision.asm"
                include "Prepare.asm"
                include "Detection.asm"
                include "AABB/Include.inc"

                endmodule

                endif ; ~_MODULE_GAME_OBJECT_COLLISION_INCLUDE_
