
                ifndef _CORE_MODULE_GAME_INCLUDE_
                define _CORE_MODULE_GAME_INCLUDE_

                include "EntryPoint.asm"
                include "Loop.asm"
                include "Interrupt.asm"
                include "Input/Include.inc"
                include "Render/Include.inc"
                include "World/Include.inc"

                endif ; ~_CORE_MODULE_GAME_INCLUDE_
