
                ifndef _CORE_MODULE_GAME_INCLUDE_
                define _CORE_MODULE_GAME_INCLUDE_

                include "EntryPoint.asm"                                        ; первый
                include "Loop.asm"                                              ; второй
                include "Render/Include.inc"

                ; include "Initialize/Include.inc"
                ; include "Input/Include.inc"
                ; include "World/Include.inc"
                ; include "Pause/Include.inc"

                endif ; ~_CORE_MODULE_GAME_INCLUDE_
