
                ifndef _MODULE_GAME_RENDER_WASTELAND_INCLUDE_
                define _MODULE_GAME_RENDER_WASTELAND_INCLUDE_

                module Render

                include "Draw.asm"
                include "Prepare.asm"
                include "UI_Draw.asm"
                include "OBJ_Draw.asm"
                include "VFX_Draw.asm"
                include "UI/Include.inc"
                include "Sort/Include.inc"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_WASTELAND_INCLUDE_
