
                ifndef _CORE_MODULE_GRAPHICS_SMOKE_INCLUDE_
                define _CORE_MODULE_GRAPHICS_SMOKE_INCLUDE_

                module Smoke

Anim_0          incbin "Core/Module/Graphics/VFX/Smoke/Original/Smoke_0.spr"
Anim_1          incbin "Core/Module/Graphics/VFX/Smoke/Original/Smoke_1.spr"
Anim_2          incbin "Core/Module/Graphics/VFX/Smoke/Original/Smoke_2.spr"
Anim_3          incbin "Core/Module/Graphics/VFX/Smoke/Original/Smoke_3.spr"
Anim_4          incbin "Core/Module/Graphics/VFX/Smoke/Original/Smoke_4.spr"
Anim_5          incbin "Core/Module/Graphics/VFX/Smoke/Original/Smoke_5.spr"
Anim_6          incbin "Core/Module/Graphics/VFX/Smoke/Original/Smoke_6.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_SMOKE_INCLUDE_
