
                module SpriteInfo
Smoke:           
                FSprite { { 5, 2, 8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Smoke.Anim_6 } }
                FSprite { { 7, 0, 8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Smoke.Anim_5 } }
                FSprite { { 8, 0, 8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Smoke.Anim_4 } }
                FSprite { { 8, 0, 8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Smoke.Anim_3 } }
                FSprite { { 8, 0, 8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Smoke.Anim_2 } }
                FSprite { { 8, 0, 8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Smoke.Anim_1 } }
                FSprite { { 5, 3, 8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Smoke.Anim_0 } }

                endmodule
