
                ifndef _CORE_MODULE_GRAPHICS_EXPLOSION_INCLUDE_
                define _CORE_MODULE_GRAPHICS_EXPLOSION_INCLUDE_

                module Explosion
Anim_0          incbin "Core/Module/Graphics/VFX/Explosion/Original/Explosion_0.spr"
Anim_1          incbin "Core/Module/Graphics/VFX/Explosion/Original/Explosion_1.spr"
Anim_2          incbin "Core/Module/Graphics/VFX/Explosion/Original/Explosion_2.spr"
Anim_3          incbin "Core/Module/Graphics/VFX/Explosion/Original/Explosion_3.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_EXPLOSION_INCLUDE_
