
                module SpriteInfo
Explosion:           
                FSprite { { 16, 0-8, 16, 0+6 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_3 } }
                FSprite { { 15, 2-8, 13, 1+6 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_2 } }
                FSprite { { 12, 2-8, 11, 2+6 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_1 } }
                FSprite { {  6, 5-8,  6, 5+6 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_0 } }

                endmodule
