
                module SpriteInfo
Explosion:           
                FSprite { { 16, 0+2, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_3 } }
                FSprite { { 15, 2+2, 13, 1 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_2 } }
                FSprite { { 12, 2+2, 11, 2 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_1 } }
                FSprite { {  6, 5+2,  6, 5 }, 0, { Page.Graphics.Pack1, Graphics.Explosion.Anim_0 } }

                endmodule
