
                ifndef _CORE_MODULE_DRAW_WORLD_FUNCTION_NO_SHIFT_INCLUDE_
                define _CORE_MODULE_DRAW_WORLD_FUNCTION_NO_SHIFT_INCLUDE_

                module Functions

                include "NoShift_Left.asm"
                include "NoShift_Center.asm"
                include "NoShift_Right.asm"

                endmodule

                endif ; ~ _CORE_MODULE_DRAW_WORLD_FUNCTION_NO_SHIFT_INCLUDE_
