
                ifndef _CORE_MODULE_OPEN_WORLD_INCLUDE_
                define _CORE_MODULE_OPEN_WORLD_INCLUDE_

                module OpenWorld

                include "Utils/Include.inc"
                include "Object/Include.inc"
                include "Wasteland/Include.inc"
                include "Gen_Game.asm"

                endmodule

                endif ; ~_CORE_MODULE_OPEN_WORLD_INCLUDE_
