
                ifndef _CORE_MODULE_GRAPHICS_MARKERS_INCLUDE_
                define _CORE_MODULE_GRAPHICS_MARKERS_INCLUDE_

                module UI
Markers:
._0             incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_0.spr"
._1_0           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_1_0.spr"
._1_1           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_1_1.spr"
._2_0           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_2_0.spr"
._2_1           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_2_1.spr"
._2_2           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_2_2.spr"
._3_0           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_3_0.spr"
._3_1           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_3_1.spr"
._3_2           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_3_2.spr"
._3_3           incbin "Core/Module/Graphics/UI/MapMarkers/Original/Marker_3_3.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_MARKERS_INCLUDE_
