
                module SpriteInfo
Markers:
.Settle         FSprite { { 4, -2, 6, -2 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._0 } }

.Player         FSprite { { 6, -5, 5, -2 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._1_0 } }
                FSprite { { 6, -5, 5, -2 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._1_1 } }

.Flag           FSprite { { 5, -4, 4,  0 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._2_0 } }
                FSprite { { 5, -4, 4,  0 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._2_1 } }
                FSprite { { 5, -4, 4,  0 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._2_0 } }
                FSprite { { 5, -4, 4,  0 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._2_2 } }

.InterestPoint  FSprite { { 3, -1, 6, -2 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._3_0 } }
                FSprite { { 3, -1, 6, -2 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._3_1 } }
                FSprite { { 3, -1, 6, -2 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._3_2 } }
                FSprite { { 3, -1, 6, -2 }, 0, { Page.Graphics.Pack1, Graphics.UI.Markers._3_3 } }

                endmodule
