
                ifndef _MODULE_GAME_RENDER_MAIN_MENU_INCLUDE_
                define _MODULE_GAME_RENDER_MAIN_MENU_INCLUDE_

                module Render

                include "Draw.asm"
                include "Main.asm"
                include "StartGame.asm"
                include "Continue.asm"
                include "Options.asm"
                include "RedefineKeys.asm"
                include "Fadeout.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_MAIN_MENU_INCLUDE_
