
                module SpriteInfo
Car_B:           
                FSprite { { 15, 4, 21, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_4 } }       ; 0000 - 0.0°     right
                FSprite { { 16, 4, 21, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_3 } }       ; 0001 - 22.5°
                FSprite { { 19, 3, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_2 } }       ; 0010 - 45.0°    up-right
                FSprite { { 19, 2, 21, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_1 } }       ; 0011 - 67.5°
                FSprite { { 19, 2, 14, 5 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_0 } }       ; 0100 - 90.0°    up
                FSprite { { 19, 2, 21, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_F } }       ; 0101 - 112.5°
                FSprite { { 19, 3, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_E } }       ; 0110 - 135.0°   up-left
                FSprite { { 16, 4, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_D } }       ; 0111 - 157.5°

                FSprite { { 15, 4, 21, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_C } }       ; 1000 - 180.0°   left
                FSprite { { 19, 2, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_B } }       ; 1001 - 202.5°
                FSprite { { 21, 1, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_A } }       ; 1010 - 225.0°   down-left
                FSprite { { 22, 0, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_9 } }       ; 1011 - 247.0°
                FSprite { { 20, 0, 14, 5 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_8 } }       ; 1100 - 270.0°   down
                FSprite { { 22, 0, 20, 2 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_7 } }       ; 1101 - 292.5°
                FSprite { { 21, 1, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_6 } }       ; 1110 - 315.0°   down-right
                FSprite { { 19, 2, 22, 1 }, 0, { Page.Graphics.Pack1, Graphics.Car_B.Anim_5 } }       ; 1111 - 337.5°

                endmodule
