
                ifndef _MODULE_GAME_RENDER_UI_INCLUDE_
                define _MODULE_GAME_RENDER_UI_INCLUDE_

                module UI
                
                include "Icons.asm"
                include "Bars.asm"
                include "Frame.asm"
                include "Draw.asm"
                include "Initialize.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_UI_INCLUDE_
