
                ifndef _CORE_MODULE_TEXT_SETTLEMENT_ADJECTIVE_
                define _CORE_MODULE_TEXT_SETTLEMENT_ADJECTIVE_

                lua allpass
                Convert("сухой")
                endlua
                lua allpass
                Convert("ветренный")
                endlua
                lua allpass
                Convert("старый")
                endlua
                lua allpass
                Convert("ржавый")
                endlua
                lua allpass
                Convert("скрипучий")
                endlua
                lua allpass
                Convert("атомный")
                endlua
                lua allpass
                Convert("прыгучий")
                endlua
                lua allpass
                Convert("ноющий")
                endlua
                lua allpass
                Convert("святой")
                endlua
                lua allpass
                Convert("кручёный")
                endlua

                lua allpass
                Convert("шершавый")
                endlua
                lua allpass
                Convert("скалящийся")
                endlua
                lua allpass
                Convert("кривой")
                endlua
                lua allpass
                Convert("текучий")
                endlua
                lua allpass
                Convert("пахучий")
                endlua
                lua allpass
                Convert("мёртвый")
                endlua
                lua allpass
                Convert("затерянный")
                endlua
                lua allpass
                Convert("толстый")
                endlua
                lua allpass
                Convert("сыпучий")
                endlua
                lua allpass
                Convert("плакучий")
                endlua

                lua allpass
                Convert("красивый")
                endlua
                lua allpass
                Convert("занудный")
                endlua
                lua allpass
                Convert("гутаперчивый")
                endlua
                lua allpass
                Convert("некрасивый")
                endlua
                lua allpass
                Convert("смердящий")
                endlua
                lua allpass
                Convert("великий")
                endlua
                lua allpass
                Convert("агонизирующий")
                endlua
                lua allpass
                Convert("нетленный")
                endlua
                lua allpass
                Convert("горючий")
                endlua
                lua allpass
                Convert("паранормальный")
                endlua

                lua allpass
                Convert("воинственный")
                endlua
                lua allpass
                Convert("двуликий")
                endlua

                endif ; ~ _CORE_MODULE_TEXT_SETTLEMENT_ADJECTIVE_