
                ifndef _CORE_MODULE_TEXT_SETTLEMENT_BUILD_
                define _CORE_MODULE_TEXT_SETTLEMENT_BUILD_
Build
.Entrance       lua allpass
                Convert("Вход")
                endlua
.ResidentialArea lua allpass
                Convert("Жилой район")
                endlua
.Worehouse      lua allpass
                Convert("Сборщики лома")
                endlua
.ShoppingArea   lua allpass
                Convert("Торговый район")
                endlua
.Bar            lua allpass
                Convert("Бар")
                endlua
.Workshop       lua allpass
                Convert("Мастерская")
                endlua
.Priston        lua allpass
                Convert("Тюрьма")
                endlua
.RadioTower     lua allpass
                Convert("Радиовышка")
                endlua

                endif ; ~ _CORE_MODULE_TEXT_SETTLEMENT_BUILD_
