
                ifndef _CORE_MODULE_TEXT_SETTLEMENT_NOUN_
                define _CORE_MODULE_TEXT_SETTLEMENT_NOUN_
                
                lua allpass
                Convert("Слип")
                endlua
                lua allpass
                Convert("сосок")
                endlua
                lua allpass
                Convert("глушитель")
                endlua
                lua allpass
                Convert("кактус")
                endlua
                lua allpass
                Convert("выползень")
                endlua
                lua allpass
                Convert("кардан")
                endlua
                lua allpass
                Convert("прыгун")
                endlua
                lua allpass
                Convert("генератор")
                endlua
                lua allpass
                Convert("бак")
                endlua
                lua allpass
                Convert("песок")
                endlua

                lua allpass
                Convert("клюв")
                endlua
                lua allpass
                Convert("грызун")
                endlua
                lua allpass
                Convert("петард")
                endlua
                lua allpass
                Convert("пистолет")
                endlua
                lua allpass
                Convert("череп")
                endlua
                lua allpass
                Convert("капкан")
                endlua
                lua allpass
                Convert("запал")
                endlua
                lua allpass
                Convert("ствол")
                endlua
                lua allpass
                Convert("рычаг")
                endlua
                lua allpass
                Convert("котелок")
                endlua

                lua allpass
                Convert("рыдван")
                endlua
                lua allpass
                Convert("шарикоподшипник")
                endlua
                lua allpass
                Convert("самострел")
                endlua
                lua allpass
                Convert("пугач")
                endlua
                lua allpass
                Convert("патрон")
                endlua
                lua allpass
                Convert("выхлоп")
                endlua
                lua allpass
                Convert("бархан")
                endlua
                lua allpass
                Convert("выродок")
                endlua
                lua allpass
                Convert("радиатор")
                endlua
                lua allpass
                Convert("пёс")
                endlua

                lua allpass
                Convert("паразит")
                endlua
                lua allpass
                Convert("сверчок")
                endlua

                endif ; ~ _CORE_MODULE_TEXT_SETTLEMENT_NOUN_