
                ifndef _CORE_MODULE_TEXT_START_GAME_
                define _CORE_MODULE_TEXT_START_GAME_
StartGame
.MapGenerator   lua allpass
                Convert ("Настройки игры")
                endlua
.KeyGenerator   lua allpass
                Convert("Ключ генератора")
                endlua
.Difficulty     lua allpass
                Convert("Сложность")
                endlua
.Climate        lua allpass
                Convert("Климат")
                endlua
.MapSize        lua allpass
                Convert("Размер карты")
                endlua
.SettlementsNum lua allpass
                Convert("Количество поселений")
                endlua
.DistSettlements lua allpass
                Convert("Расстояние между поселениями")
                endlua
.FriendlySettlement lua allpass
                Convert("Частота дружественных поселений")
                endlua
.NeutralSettlement lua allpass
                Convert("Частота нейтральных поселений")
                endlua
.HostileSettlement lua allpass
                Convert("Частота враждебных поселений")
                endlua
.Play           lua allpass
                Convert("Играть")
                endlua

Difficulty
.Easy           lua allpass
                Convert("лёгко")
                endlua
.Normal         lua allpass
                Convert("нормально")
                endlua
.Nightmare      lua allpass
                Convert("кошмарно")
                endlua
.Hardcore       lua allpass
                Convert("ужасно")
                endlua

Climate
.Temperate      lua allpass
                Convert("умеренный")
                endlua
.Harsh          lua allpass
                Convert("суровый")
                endlua
MapSize
.Small          lua allpass
                Convert("маленькая")
                endlua
.Average        lua allpass
                Convert("средняя")
                endlua
.Big            lua allpass
                Convert("большая")
                endlua

                endif ; ~ _CORE_MODULE_TEXT_START_GAME_
