
                ifndef _CORE_MODULE_GRAPHICS_UI_ARROW_INCLUDE_
                define _CORE_MODULE_GRAPHICS_UI_ARROW_INCLUDE_

                module Arrow

Anim_0          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_0.spr"
Anim_1          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_1.spr"
Anim_2          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_2.spr"
Anim_3          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_3.spr"
Anim_4          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_4.spr"
Anim_5          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_5.spr"
Anim_6          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_6.spr"
Anim_7          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_7.spr"
Anim_8          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_8.spr"
Anim_9          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_9.spr"
Anim_A          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_A.spr"
Anim_B          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_B.spr"
Anim_C          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_C.spr"
Anim_D          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_D.spr"
Anim_E          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_E.spr"
Anim_F          incbin "Core/Module/Graphics/UI/Arrow/Original/Arrow_F.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_UI_ARROW_INCLUDE_
