
                ifndef _CONST_GAME_SCREEN_MAP_
                define _CONST_GAME_SCREEN_MAP_
SCR_MAP_POS_X   EQU 1                                                           ; положение карты мира на экране по горизонтали (в знакоместах)
SCR_MAP_POS_Y   EQU 1                                                           ; положение карты мира на экране по вертикали   (в знакоместах)
SCR_MAP_SIZE_X  EQU 22                                                          ; размер карты мира на экране по горизонтали    (в знакоместах)
SCR_MAP_SIZE_Y  EQU 22                                                          ; размер карты мира на экране по вертикали      (в знакоместах)

                endif ; ~_CONST_GAME_SCREEN_MAP_
