
                ifndef _CONST_INCLUDES_
                define _CONST_INCLUDES_

                include "Color.inc"

                include "Memory.inc"
                include "MemoryMap.inc"
                include "MemoryMapGame.inc"
                include "MemoryMapObject.inc"
                include "MemoryMapGraphics.inc"

                include "Game.inc"
                include "Kernel.inc"
                include "Input.inc"
                include "World.inc"
                include "Render.inc"
                include "Interrupt.inc"

                include "RenderBuffer.inc"
                include "SharedBuffer.inc"
                include "SortBuffer.inc"

                include "GameScreenWorld.inc"
                include "GameWorldSprite.inc"

                include "ObjectType.inc"

                endif ; ~_CONST_INCLUDES_
