
                ifndef _CONST_INCLUDES_
                define _CONST_INCLUDES_

                include "Color.inc"

                include "Memory.inc"
                include "MemoryMap.inc"
                include "MemoryMapGame.inc"
                include "MemoryMapGraphics.inc"
                include "MemoryMapPack_0.inc"
                include "MemoryMapPack_1.inc"
                include "MemoryMapPack_6.inc"

                include "Map.inc"
                include "Menu.inc"
                include "Game.inc"
                include "Kernel.inc"
                include "Input.inc"
                include "World.inc"
                include "Config.inc"
                include "Render.inc"
                include "Region.inc"
                include "Hardware.inc"
                include "Variables.inc"
                include "Charecter.inc"
                include "Interrupt.inc"
                include "Settlement.inc"
                include "GenerateWorld.inc"
                include "VoronoiDiagram.inc"

                include "RenderBuffer.inc"
                include "SharedBuffer.inc"
                include "SortBuffer.inc"

                include "Player.inc"

                include "UI.inc"
                include "GameScreenWorld.inc"
                include "GameWorldSprite.inc"
                include "GameWorldCamera.inc"

                include "ObjectType.inc"
                include "ObjectType_Decal.inc"
                include "ObjectType_Particle.inc"
                include "ObjectType_Interaction.inc"

                endif ; ~_CONST_INCLUDES_
