
                ifndef _CONST_MAP_
                define _CONST_MAP_

VISIBLE_MAP_SIZE_SCR        EQU 22                                              ; видимый размер карты на экране
MAP_SIZE_SMALL_SQUARED      EQU 42                                              ; размер карты "маленькая"      (42x42)
MAP_SIZE_AVERAGE_SQUARED    EQU 57                                              ; размер карты "средняя"        (57x57)
MAP_SIZE_BIG_SQUARED        EQU 72                                              ; размер карты "большая"        (72x72)

                endif ; ~_CONST_MAP_
