
                ifndef _CONST_MAP_
                define _CONST_MAP_

MAP_SIZE_SMALL_SQUARED      EQU 45                                              ; размер карты "маленький"      (45x45)
MAP_SIZE_AVERAGE_SQUARED    EQU 64                                              ; размер карты "средний"        (64x64)
MAP_SIZE_BIG_SQUARED        EQU 90                                              ; размер карты "большой"        (90x90)

                endif ; ~_CONST_MAP_
