
                ifndef _CONST_OBJECT_TYPE_DECAL_
                define _CONST_OBJECT_TYPE_DECAL_

OBJECT_CACTUS_A EQU 0x00                                                        ; кактус A
OBJECT_CACTUS_B EQU 0x01                                                        ; кактус B
OBJECT_CACTUS_C EQU 0x02                                                        ; кактус C
OBJECT_GRASS    EQU 0x03                                                        ; трава
OBJECT_SCULL_A  EQU 0x04                                                        ; череп A
OBJECT_LOG_A    EQU 0x05                                                        ; бревно A
OBJECT_STONE_A  EQU 0x06                                                        ; камень A
OBJECT_STONE_B  EQU 0x07                                                        ; камень B
OBJECT_STONE_C  EQU 0x08                                                        ; камень C
OBJECT_LOG_B    EQU 0x09                                                        ; бревно B
OBJECT_LOG_C    EQU 0x0A                                                        ; бревно C
OBJECT_DITCH_A  EQU 0x0B                                                        ; канава A
OBJECT_SCULL_B  EQU 0x0C                                                        ; череп B
OBJECT_DITCH_B  EQU 0x0B                                                        ; канава B

                endif ; ~_CONST_OBJECT_TYPE_DECAL_
