
                ifndef _CONST_OBJECT_TYPE_PARTICLE_
                define _CONST_OBJECT_TYPE_PARTICLE_

PARTICLE_DUST       EQU 0x00                                                    ; пыль
PARTICLE_SMOKE      EQU 0x01                                                    ; дым
PARTICLE_EXPLOSION  EQU 0x02                                                    ; взрыв

                endif ; ~_CONST_OBJECT_TYPE_PARTICLE_
