
                ifndef _CONST_OBJECT_TYPE_INTERACTION_
                define _CONST_OBJECT_TYPE_INTERACTION_
INTERACTION_MINE    EQU 0x00                                                    ; мина


LIFETIME_MINE       EQU 0x40                                                    ; время жизни мины
DELAY_ACTIVATE_MINE EQU 0x08                                                    ; время до активации мины
                endif ; ~_CONST_OBJECT_TYPE_INTERACTION_
