
                ifndef _CONST_RENDER_FLAGS_
                define _CONST_RENDER_FLAGS_
FINISHED_BIT    EQU 0x00                                                        ; рендер завершён
GEN_BIT     EQU 0x01                                                        ; рендер завершён
INERT_BIT     EQU 0x02                                                        ; рендер завершён

                endif ; ~_CONST_RENDER_FLAGS_
