
                ifndef _CONST_WORLD_FLAGS_
                define _CONST_WORLD_FLAGS_
INERT_BIT     EQU 0x02                                                        ; рендер завершён

WORLD_LEFT_BIT  EQU 0x04                                                        ; бит скрола влево
WORLD_RIGHT_BIT EQU 0x05                                                        ; бит скрола вправо
WORLD_UP_BIT    EQU 0x06                                                        ; бит скрола вверх
WORLD_DOWN_BIT  EQU 0x07                                                        ; бит скрола вниз

                endif ; ~_CONST_WORLD_FLAGS_
