
                ifndef _CORE_MODULE_GRAPHICS_CAR_1_INCLUDE_
                define _CORE_MODULE_GRAPHICS_CAR_1_INCLUDE_

                module Car

Aim_0           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_0.spr"
Aim_1           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_1.spr"
Aim_2           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_2.spr"
Aim_3           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_3.spr"
Aim_4           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_4.spr"
Aim_5           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_5.spr"
Aim_6           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_6.spr"
Aim_7           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_7.spr"
Aim_8           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_8.spr"
Aim_9           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_9.spr"
Aim_A           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_A.spr"
Aim_B           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_B.spr"
Aim_C           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_C.spr"
Aim_D           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_D.spr"
Aim_E           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_E.spr"
Aim_F           incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_F.spr"

                ; include "Core/Module/Graphics/Car/A/Sprite/Info.inc"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_CAR_1_INCLUDE_
