
                ifndef _CORE_MODULE_GRAPHICS_CAR_1_INCLUDE_
                define _CORE_MODULE_GRAPHICS_CAR_1_INCLUDE_

                module Car_A

Anim_0          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_0.spr"
Anim_1          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_1.spr"
Anim_2          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_2.spr"
Anim_3          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_3.spr"
Anim_4          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_4.spr"
Anim_5          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_5.spr"
Anim_6          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_6.spr"
Anim_7          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_7.spr"
Anim_8          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_8.spr"
Anim_9          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_9.spr"
Anim_A          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_A.spr"
Anim_B          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_B.spr"
Anim_C          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_C.spr"
Anim_D          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_D.spr"
Anim_E          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_E.spr"
Anim_F          incbin "Core/Module/Graphics/Car/A/Sprite/Original/Car_0_F.spr"

                ; include "Core/Module/Graphics/Car/A/Sprite/Info.inc"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_CAR_1_INCLUDE_
