
                ifndef _STRUCTURE_ABANDONED_
                define _STRUCTURE_ABANDONED_

                struct FAbandoned                                               ; структура описывающая заброшенных/покинутых поселений в зоне
RegionID        DB #00                                                          ; индекс структуры региона поселения    [1 байт]

                ends

                endif ; ~_STRUCTURE_ABANDONED_
