
                ifndef _STRUCTURE_CHARACTER_
                define _STRUCTURE_CHARACTER_

                struct FCharacter
Health          DB #00                                                          ; уровень очков здоровья
Gas             DB #00                                                          ; уровень очков топлива
Turbo           DB #00                                                          ; уровень очков ускорения

                ends

                endif ; ~_STRUCTURE_CHARACTER_
