
                ifndef _STRUCTURE_DUNGEON_
                define _STRUCTURE_DUNGEON_

                struct FDungeon                                                 ; структура описывающая подземелья на карте
RegionID        DB #00                                                          ; индекс структуры региона поселения    [1 байт]
                ends

                endif ; ~_STRUCTURE_DUNGEON_
