
                ifndef _STRUCT_INCLUDE_
                define _STRUCT_INCLUDE_

                include "Base.inc"
                include "Config.inc"
                include "Game.inc"
                include "Time.inc"
                include "Player.inc"
                include "Settlement.inc"
                include "VoronoiDiagram.inc"

                include "Font.inc"
                include "AABB.inc"
                include "Sprite.inc"
                include "Dialog.inc"

                include "Character.inc"
                include "BehaviorTree.inc"

                include "Object.inc"
                include "Object_Decal.inc"
                include "Object_Particle.inc"
                include "Object_Interaction.inc"

                endif ; ~_STRUCT_INCLUDE_
