
                ifndef _STRUCT_INCLUDE_
                define _STRUCT_INCLUDE_

                include "Base.inc"
                include "Config.inc"
                include "Game.inc"
                include "Player.inc"

                include "AABB.inc"
                include "Sprite.inc"

                include "Character.inc"
                include "BehaviorTree.inc"

                include "Object.inc"
                include "Object_Decal.inc"
                include "Object_Particle.inc"

                endif ; ~_STRUCT_INCLUDE_
