
                ifndef _CORE_MODULE_OBJECT_INITIALIZE_INCLUDE_
                define _CORE_MODULE_OBJECT_INITIALIZE_INCLUDE_

                module Initialize

                include "Initialize.asm"
                include "Spawn.asm"
                include "Spawn_NPC.asm"
                include "Spawn_Player.asm"
                include "Spawn_Decal.asm"
                include "Spawn_Particle.asm"

                endmodule

                endif ; ~ _CORE_MODULE_OBJECT_INITIALIZE_INCLUDE_
