
                ifndef _CORE_MODULE_OPEN_WORLD_GENERATE_METADATA_INCLUDE_
                define _CORE_MODULE_OPEN_WORLD_GENERATE_METADATA_INCLUDE_

                module Metadata

                include "Add.asm"
                include "RandDungeon.asm"
                include "RandHabitats.asm"
                include "RandAbandoned.asm"
                include "RandSettlement.asm"

                endmodule

                endif ; ~_CORE_MODULE_OPEN_WORLD_GENERATE_METADATA_INCLUDE_
