
                ifndef _MODULE_GAME_RENDER_MAP_INCLUDE_
                define _MODULE_GAME_RENDER_MAP_INCLUDE_

                module Render

                include "UI/Include.inc"

                include "Draw.asm"
                include "DisplayRegion.asm"
                include "DisplayMarkers.asm"
                include "DisplayMapFrame.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_MAP_INCLUDE_
