
                ; compressor    https://github.com/emmanuel-marty/salvador
                ; decompressor  https://github.com/einar-saukas/ZX0
                
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Weapon/Original/None.spr Core/Module/Graphics/UI/Weapon/Compressed/None.spr.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Weapon/Original/MachineGun.spr Core/Module/Graphics/UI/Weapon/Compressed/MachineGun.spr.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Weapon/Original/Mine.spr Core/Module/Graphics/UI/Weapon/Compressed/Mine.spr.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Weapon/Original/Rocket.spr Core/Module/Graphics/UI/Weapon/Compressed/Rocket.spr.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Weapon/Original/RepairKit.spr Core/Module/Graphics/UI/Weapon/Compressed/RepairKit.spr.ar"
