
                ifndef _CORE_MODULE_OPEN_WORLD_OBJECT_COLLISION_TYPES_INCLUDE_
                define _CORE_MODULE_OPEN_WORLD_OBJECT_COLLISION_TYPES_INCLUDE_
                
                module Types

                include "Handler.asm"
                include "Decal.asm"
                include "Mine.asm"

                endmodule

                endif ; ~_CORE_MODULE_OPEN_WORLD_OBJECT_COLLISION_TYPES_INCLUDE_
