
                ifndef _CORE_MODULE_AI_TASK_INCLUDE_
                define _CORE_MODULE_AI_TASK_INCLUDE_

                module BTT

                include "AttackTo.asm"
                include "CheckEnemy.asm"
                include "Idle.asm"
                include "MoveTo.asm"
                include "Wait.asm"

                endmodule

                include "TaskIndixes.inc"

                endif ; ~ _CORE_MODULE_AI_TASKS_INCLUDE_