
                ifndef _CORE_AI_BEHAVIOR_TASK_INDICES_INCLUDE_
                define _CORE_AI_BEHAVIOR_TASK_INDICES_INCLUDE_
BTT_IDLE        EQU 0x00                                                        ; Idle
BTT_MTO         EQU 0x01                                                        ; MoveTo
BTT_ATO         EQU 0x02                                                        ; AttackTo
BTT_CE          EQU 0x03                                                        ; CheckEnemy
BTT_W           EQU 0x04                                                        ; Wait

                endif ; ~ _CORE_AI_BEHAVIOR_TASK_INDICES_INCLUDE_