
                ifndef _CORE_MODULE_GRAPHICS_DUST_INCLUDE_
                define _CORE_MODULE_GRAPHICS_DUST_INCLUDE_

                module Dust

Anim_0          incbin "Core/Module/Graphics/VFX/Dust/Original/Dust_0.spr"
Anim_1          incbin "Core/Module/Graphics/VFX/Dust/Original/Dust_1.spr"
Anim_2          incbin "Core/Module/Graphics/VFX/Dust/Original/Dust_2.spr"
Anim_3          incbin "Core/Module/Graphics/VFX/Dust/Original/Dust_3.spr"
Anim_4          incbin "Core/Module/Graphics/VFX/Dust/Original/Dust_4.spr"
Anim_5          incbin "Core/Module/Graphics/VFX/Dust/Original/Dust_5.spr"
Anim_6          incbin "Core/Module/Graphics/VFX/Dust/Original/Dust_6.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_DUST_INCLUDE_
