
                module SpriteInfo
Dust:           
                FSprite { { 5, 2, 8, 0 }, 0, { Page.Graphics.Pack1, Graphics.Dust.Anim_6 } }
                FSprite { { 7, 0, 8, 0 }, 0, { Page.Graphics.Pack1, Graphics.Dust.Anim_5 } }
                FSprite { { 8, 0, 8, 0 }, 0, { Page.Graphics.Pack1, Graphics.Dust.Anim_4 } }
                FSprite { { 8, 0, 8, 0 }, 0, { Page.Graphics.Pack1, Graphics.Dust.Anim_3 } }
                FSprite { { 8, 0, 8, 0 }, 0, { Page.Graphics.Pack1, Graphics.Dust.Anim_2 } }
                FSprite { { 8, 0, 8, 0 }, 0, { Page.Graphics.Pack1, Graphics.Dust.Anim_1 } }
                FSprite { { 5, 3, 8, 0 }, 0, { Page.Graphics.Pack1, Graphics.Dust.Anim_0 } }

                endmodule
