
                ; compressor    https://github.com/emmanuel-marty/salvador
                ; decompressor  https://github.com/einar-saukas/ZX0
                
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Settlement/Original/Frame.spr Core/Module/Graphics/UI/Settlement/Compressed/Frame.spr.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Settlement/Original/ArtFrame_0.spr Core/Module/Graphics/UI/Settlement/Compressed/ArtFrame_0.spr.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Settlement/Original/ArtFrame_1.spr Core/Module/Graphics/UI/Settlement/Compressed/ArtFrame_1.spr.ar"
