
                ifndef _MODULE_GAME_RENDER_PAUSE_MENU_INCLUDE_
                define _MODULE_GAME_RENDER_PAUSE_MENU_INCLUDE_

                module Pause                                                    ; вынести в страницу 
                                                                                ; базовы блок копируется в нижнию часть ОЗУ

                include "Draw.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_PAUSE_MENU_INCLUDE_
