
                ifndef _MODULE_GAME_RENDER_WASTELAND_SORT_INCLUDE_
                define _MODULE_GAME_RENDER_WASTELAND_SORT_INCLUDE_

                module Sort                                                     ; вынести в страницу объектов
                
                include "Sort.asm"
                include "Prepare.asm"
                include "Quicksort.asm"

                endmodule

                endif ; ~_MODULE_GAME_RENDER_WASTELAND_SORT_INCLUDE_
