
                ifndef _BUILDER_INCLUDES_
                define _BUILDER_INCLUDES_

                include "Const/Include.inc"
                include "Config/Include.inc"
                include "Macro/Include.inc"
                ; include "Struct/Include.inc"

                ; version build
                define BUILD 0
                define MAJOR 0
                define MINOR 1

                define TAP_FILENAME "RPG.tap"                                   ; имя образа

                endif ; ~_BUILDER_INCLUDES_
