
                ifndef _BUILDER_INCLUDES_
                define _BUILDER_INCLUDES_

                include "Const/Include.inc"
                include "Config/Include.inc"
                include "Macro/Include.inc"
                include "Struct/Include.inc"

                ; version build
                define BUILD 0
                define MAJOR 0
                define MINOR 2

                define TAP_FILENAME "RPG.tap"                                   ; имя образа
                define SNA_FILENAME "RPG.sna"                                   ; имя образа для отладки

                endif ; ~_BUILDER_INCLUDES_
