
                ifndef _MODULE_GAME_INITIALIZE_INCLUDE_
                define _MODULE_GAME_INITIALIZE_INCLUDE_

                module Initialize

                include "Core/Base.asm"
                include "Core/Input.asm"
                include "Core/Player.asm"
                include "Core/PlayGame.asm"

                endmodule

                endif ; ~_MODULE_GAME_INITIALIZE_INCLUDE_
