
                ; compressor    https://github.com/emmanuel-marty/salvador
                ; decompressor  https://github.com/einar-saukas/ZX0
                
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Charecter/Original/Charecter_0.pack Core/Module/Graphics/UI/Charecter/Compressed/Charecter_0.pack.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Charecter/Original/Charecter_1.pack Core/Module/Graphics/UI/Charecter/Compressed/Charecter_1.pack.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Charecter/Original/Charecter_2.pack Core/Module/Graphics/UI/Charecter/Compressed/Charecter_2.pack.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Charecter/Original/Charecter_3.pack Core/Module/Graphics/UI/Charecter/Compressed/Charecter_3.pack.ar"
                shellexec "Tools\Compressor\salvador.exe -v Core/Module/Graphics/UI/Charecter/Original/Charecter_4.pack Core/Module/Graphics/UI/Charecter/Compressed/Charecter_4.pack.ar"
