
                ifndef _CORE_MODULE_FUNCTIONS_INCLUDE_
                define _CORE_MODULE_FUNCTIONS_INCLUDE_

                module Functions

                include "Fadeout.asm"                                           ; (0)
                include "ScreenCopy.asm"                                        ; (1)

                endmodule

                endif ; ~_CORE_MODULE_FUNCTIONS_INCLUDE_
