
                ifndef _CORE_MODULE_GRAPHICS_DECALS_INCLUDE_
                define _CORE_MODULE_GRAPHICS_DECALS_INCLUDE_

                module Decals
_0              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_0.spr"
_1              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_1.spr"
_2              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_2.spr"
_3              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_3.spr"
_4              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_4.spr"
_5              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_5.spr"
_6              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_6.spr"
_7              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_7.spr"
_8              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_8.spr"
_9              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_9.spr"
_A              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_A.spr"
_B              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_B.spr"
_C              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_C.spr"
_D              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_D.spr"
_E              incbin "Core/Module/Graphics/Tile/World/Sprite/Original/Decal/Decal_E.spr"

                endmodule

                endif ; ~_CORE_MODULE_GRAPHICS_DECALS_INCLUDE_
