
                module SpriteInfo
Decals:           
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._0 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._1 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._2 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._3 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._4 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._5 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._6 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._7 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._8 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._9 } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._A } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._B } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._C } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._D } }
                FSprite { { 16, 0, 16, 0 }, 0, { Page.Graphics.Pack1, Graphics.Decals._E } }

                endmodule
